---

version: "3.9"

services:
  btsd:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TRAEFIK_HOST: http://traefik.mgmt
      TRAEFIK_USERNAME: calvin
      TRAEFIK_PASSWORD: ${TRAEFIK_PASSWORD}
