---

version: "3.9"

services:
  btsd:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TRAEFIK_URL: http://traefik.mgmt
      TRAEFIK_USERNAME: calvin
      TRAEFIK_PASSWORD: ${TRAEFIK_PASSWORD}
      LOG_LEVEL: debug
      INTERVAL: 30
      OUTPUT_DIR: /blackbox-traefik-sd/
    volumes:
      - type: bind
        source: /apps/prometheus/blackbox-traefik-sd
        target: /blackbox-traefik-sd
    networks:
      - mgmt

networks:
  mgmt:
    external: true
